# Generated by Django 4.2.4 on 2023-09-10 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("student_management_app", "0002_onlineclassroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="student_management_app.courses",
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="profile_pic",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
